import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/components/ToastProvider/ToastProvider";
import NotificationListner from "@/components/NotificationListener/NotificationListner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          {children}
          <NotificationListner />
        </ToastProvider>
      </body>
    </html>
  );
}
